services:
  - type: web
    name: ragflow-web
    plan: pro
    runtime: docker
    dockerfilePath: Dockerfile
    numInstances: 1
    disk:
      name: docstore
      mountPath: /ragflow/storage
      sizeGB: 20
    envVars:
      - key: RENDER
        value: "true"
      - key: PORT
        value: 10000
      - key: DOC_ENGINE
        value: "elasticsearch"
      - key: DOC_STORE_ROOT
        value: /ragflow/storage
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY 
        sync: false
      - key: ELASTICSEARCH_URL
        fromService:
          name: elasticsearch
          type: elasticsearch
          property: connectionString
      - key: ELASTICSEARCH_USERNAME
        value: elastic
      - key: ELASTICSEARCH_PASSWORD
        fromService:
          name: elasticsearch
          type: elasticsearch
          property: password

  - type: worker
    name: task-executor
    plan: pro
    runtime: docker
    numInstances: 1
    disk:
      name: docstore
      mountPath: /ragflow/storage
      sizeGB: 20
    envVars:
      - key: RENDER
        value: "true"
      - key: DOC_STORE_ROOT
        value: /ragflow/storage
      - key: REDIS_HOST
        value: ragflow-redis
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        value: ""
      - key: ELASTICSEARCH_URL
        fromService:
          name: ragflow-elasticsearch
          type: elasticsearch
          property: connectionString
      - key: ELASTICSEARCH_USERNAME
        value: elastic
      - key: ELASTICSEARCH_PASSWORD
        fromService:
          name: ragflow-elasticsearch
          type: elasticsearch
          property: password

  - type: redis
    name: ragflow-redis
    plan: standard
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: "Render services"
    maxmemoryPolicy: allkeys-lru

  - type: pserv
    name: elasticsearch
    env: docker
    plan: standard
    region: oregon
    autoDeploy: false
    ipAllowList:
      - source: 0.0.0.0/0
        description: "Render services"
    disk:
      name: esdata
      mountPath: /usr/share/elasticsearch/data
      sizeGB: 10
    envVars:
      - key: discovery.type
        value: single-node
      - key: ES_JAVA_OPTS
        value: "-Xms512m -Xmx512m"
      - key: cluster.name
        value: elastic

databases:
  - name: ragflow-db
    plan: basic-4gb
    postgresMajorVersion: "16"
    databaseName: ragflow_prod
    user: ragflow_admin
    region: oregon
    diskSizeGB: 20
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

# Note: Create Redis service separately in Render dashboard
