services:
  - type: web
    name: ragflow-web
    plan: pro-2
    runtime: docker
    dockerfilePath: Dockerfile
    numInstances: 1
    disk:
      name: docstore
      mountPath: /ragflow/storage
      sizeGB: 20
    envVars:
      - key: RENDER
        value: "true"
      - key: PORT
        value: 10000
      - key: DOC_ENGINE
        value: "elasticsearch"
      - key: DOC_STORE_ROOT
        value: /ragflow/storage
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY 
        sync: false
      - key: ELASTICSEARCH_URL
        value: ${ELASTICSEARCH_INSTANCE_URL}

  - type: worker
    name: task-executor 
    plan: pro-2
    runtime: docker
    numInstances: 1
    startCommand: "python rag/svr/task_executor.py"
    disk:
      name: docstore-worker
      mountPath: /ragflow/storage
      sizeGB: 20
    envVars:
      - key: RENDER
        value: "true"
      - key: DOC_STORE_ROOT
        value: /ragflow/storage
      - key: REDIS_HOST
        fromService:
          type: redis
          name: ragflow-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: ragflow-redis
          property: port
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: ragflow-redis
          property: password

databases:
  - name: ragflow-db
    plan: standard-0
    databaseName: ragflow_prod
    user: ragflow_admin
    version: "14"
    region: us-east

# Note: Create Redis service separately in Render dashboard
