services:
  - type: web
    name: minio-server
    plan: standard
    runtime: image  # Must use 'image' runtime for direct MinIO deployment
    image:
      url: docker.io/minio/minio:latest  # Correct image specification
    healthCheckPath: /minio/health/live
    dockerCommand: minio server /data --address $HOST:$PORT --console-address $HOST:$CONSOLE_PORT
    disk:
      name: minio-data
      mountPath: /data
      sizeGB: 20
    envVars:
      - key: MINIO_ROOT_USER
        generateValue: true
      - key: MINIO_ROOT_PASSWORD
        generateValue: true
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: 9000
      - key: CONSOLE_PORT  # Must match example value 9090
        value: 9090
    autoDeploy: false  # Add as per example

  - type: web
    name: minio-console
    plan: starter
    runtime: docker
    dockerContext: /  # Match example's root context
    dockerfilePath: ./Dockerfile  # Use example's Dockerfile path
    envVars:
      - key: PORT
        value: 10000
      - key: MINIO_HOST
        fromService:
          name: minio-server
          type: web
          property: host
      - key: MINIO_CONSOLE_PORT
        fromService:
          name: minio-server
          type: web
          envVarKey: CONSOLE_PORT
    autoDeploy: false  # Add as per example

  - type: web
    name: ragflow-web
    plan: pro
    runtime: docker
    dockerfilePath: Dockerfile
    numInstances: 1
    healthCheckPath: /health  # Direct property
    healthCheckTimeoutSeconds: 20  # Top-level timeout
    healthCheckIntervalSeconds: 10  # Top-level interval
    disk:
      name: docstore
      mountPath: /ragflow/storage
      sizeGB: 20
    envVars:
      - key: RENDER
        value: "true"
      - key: PORT
        value: 10000
      - key: DOC_ENGINE
        value: "elasticsearch"
      - key: DOC_STORE_ROOT
        value: /ragflow/storage
      - key: ELASTICSEARCH_URL
        value: "http://elasticsearch:9200"
      - key: ELASTICSEARCH_USERNAME
        value: elastic
      - key: ELASTICSEARCH_PASSWORD
        sync: false  # Set via Render dashboard
      - key: S3_ENDPOINT
        value: http://minio-server:9000
      - key: S3_CONSOLE_ENDPOINT
        value: https://${RENDER_SERVICE_NAME}-minio-console.onrender.com
      - key: AWS_ACCESS_KEY_ID
        fromService:
          type: pserv
          name: ragflow-minio
          envVarKey: MINIO_ROOT_USER
      - key: AWS_SECRET_ACCESS_KEY
        fromService:
          type: pserv
          name: ragflow-minio
          envVarKey: MINIO_ROOT_PASSWORD
      - fromService:
          type: redis
          name: ragflow-redis
          property: connectionString
          key: REDIS_URL

  - type: worker
    name: task-executor
    plan: pro
    runtime: docker
    numInstances: 1
    disk:
      name: docstore
      mountPath: /ragflow/storage
      sizeGB: 20
    envVars:
      - key: RENDER
        value: "true"
      - key: S3_ENDPOINT
        fromService:
          type: pserv
          name: ragflow-minio
          property: hostPort
      - key: AWS_ACCESS_KEY_ID
        fromService:
          type: pserv
          name: ragflow-minio
          envVarKey: MINIO_ROOT_USER
      - key: AWS_SECRET_ACCESS_KEY
        fromService:
          type: pserv
          name: ragflow-minio
          envVarKey: MINIO_ROOT_PASSWORD
      - fromService:
          type: redis
          name: ragflow-redis
          property: connectionString
          key: REDIS_URL
      - fromService:
          type: postgres
          name: ragflow-db
          property: connectionString
          key: DATABASE_URL

  - type: redis
    name: ragflow-redis
    plan: standard
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: "Allow all Render services"
    maxmemoryPolicy: allkeys-lru

databases:
  - name: ragflow-db
    plan: basic-4gb
    postgresMajorVersion: "16"
    databaseName: ragflow_prod
    user: ragflow_admin
    region: oregon
    diskSizeGB: 20
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
