services:
  - type: web
    name: ragflow-web
    plan: pro
    runtime: docker
    dockerfilePath: Dockerfile
    numInstances: 1
    dependsOn:
      - elasticsearch  # Must be first
      - ragflow-db
      - ragflow-redis
    disk:
      name: docstore
      mountPath: /ragflow/storage
      sizeGB: 20
    envVars:
      - key: RENDER
        value: "true"
      - key: PORT
        value: 10000
      - key: DOC_ENGINE
        value: "elasticsearch"
      - key: DOC_STORE_ROOT
        value: /ragflow/storage
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY 
        sync: false
      - key: ELASTICSEARCH_URL
        value: "http://elasticsearch:9200"
      - key: ELASTICSEARCH_TIMEOUT
        value: "60"
      - key: ELASTICSEARCH_MAX_RETRIES
        value: "15"
      - key: ELASTICSEARCH_VERIFY_CERTS
        value: "false"
      - key: ELASTICSEARCH_USERNAME
        value: elastic
      - key: ELASTICSEARCH_PASSWORD
        value: ""

  - type: worker
    name: task-executor
    plan: pro
    runtime: docker
    numInstances: 1
    disk:
      name: docstore
      mountPath: /ragflow/storage
      sizeGB: 20
    envVars:
      - key: RENDER
        value: "true"
      - key: DOC_STORE_ROOT
        value: /ragflow/storage
      - key: REDIS_HOST
        value: ragflow-redis
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        value: ""
      - key: ELASTICSEARCH_URL
        value: http://elasticsearch:9200
      - key: ELASTICSEARCH_USERNAME
        value: elastic
      - key: ELASTICSEARCH_PASSWORD
        value: ""

  - type: redis
    name: ragflow-redis
    plan: standard
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: "Render services"
    maxmemoryPolicy: allkeys-lru

  - type: pserv
    name: elasticsearch
    runtime: docker
    dockerContext: docker/
    dockerfilePath: docker/Dockerfile.elasticsearch
    plan: pro
    region: oregon
    disk:
      name: esdata
      mountPath: /usr/share/elasticsearch/data
      sizeGB: 20
    envVars:
      - key: ES_JAVA_OPTS
        value: "-Xms1g -Xmx1g"
      - key: discovery.type
        value: single-node
      - key: cluster.name
        value: "ragflow-cluster"
      - key: xpack.security.enabled
        value: "false"
      - key: network.publish_host
        value: "_site_"
      - key: http.port
        value: "9200"
      - key: transport.port
        value: "9300"

databases:
  - name: ragflow-db
    plan: basic-4gb
    postgresMajorVersion: "16"
    databaseName: ragflow_prod
    user: ragflow_admin
    region: oregon
    diskSizeGB: 20
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

# Note: Create Redis service separately in Render dashboard
