services:
  - type: web
    name: ragflow-web
    plan: pro-2
    runtime: docker
    dockerfilePath: Dockerfile
    numInstances: 1
    disk:
      name: docstore
      mountPath: /ragflow/storage
      sizeGB: 20
    envVars:
      - key: RENDER
        value: "true"
      - key: PORT
        value: 10000
      - key: DOC_ENGINE
        value: "elasticsearch"
      - key: DOC_STORE_ROOT
        value: /ragflow/storage
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY 
        sync: false
      - key: ELASTICSEARCH_URL
        value: ${ELASTICSEARCH_INSTANCE_URL}

  - type: worker
    name: task-executor 
    plan: pro-2
    runtime: docker
    numInstances: 1
    startCommand: "python rag/svr/task_executor.py"
    disk:
      name: docstore
      mountPath: /ragflow/storage
      sizeGB: 20
    envVars:
      - key: RENDER
        value: "true"
      - key: DOC_STORE_ROOT
        value: /ragflow/storage
      - key: REDIS_HOST
        value: ragflow-redis
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        value: ""

  - type: redis
    name: ragflow-redis
    plan: premium-0
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: "Render services"
    maxmemoryPolicy: allkeys-lru

databases:
  - name: ragflow-db
    plan: pro-0
    postgresMajorVersion: "16"
    databaseName: ragflow_prod
    user: ragflow_admin
    region: oregon
    diskSizeGB: 20

# Note: Create Redis service separately in Render dashboard
